// გრანტები და სტიპენდიები (UI placeholder — რეალური მონაცემები მოგვიანებით)

export const GRANT_TYPES = {
  state:    { label: "სახელმწიფო",     color: "#4f46e5" },
  uni:      { label: "უნივერსიტეტი",   color: "#0d7a5f" },
  intl:     { label: "საერთაშორისო",  color: "#e85d3a" },
  private:  { label: "კერძო ფონდი",    color: "#c026d3" },
};

export const grants = [
  {
    id: "g-state-100",
    type: "state",
    title: "100%-იანი სახელმწიფო გრანტი",
    org: "განათლების ხარისხის განვითარების ცენტრი",
    amount: "სრული დაფინანსება",
    deadline: "2026-08-15",
    description: "ეროვნული გამოცდების შედეგების მიხედვით საუკეთესო აბიტურიენტებისთვის.",
    url: "https://eqe.ge",
    eligibility: ["აბიტურიენტი", "ეროვნული გამოცდები ჩაბარებული"],
  },
  {
    id: "g-state-70",
    type: "state",
    title: "70%-იანი სახელმწიფო გრანტი",
    org: "განათლების ხარისხის განვითარების ცენტრი",
    amount: "ნაწილობრივი დაფინანსება",
    deadline: "2026-08-15",
    description: "ეროვნული გამოცდების შემდეგ შემდეგი ეტაპის აბიტურიენტებისთვის.",
    url: "https://eqe.ge",
    eligibility: ["აბიტურიენტი"],
  },
  {
    id: "g-tsu-merit",
    type: "uni",
    title: "თსუ — ნიჭიერი სტუდენტის სტიპენდია",
    org: "თბილისის სახელმწიფო უნივერსიტეტი",
    amount: "მე-2 კურსიდან, GPA ≥ 3.7",
    deadline: "2026-09-30",
    description: "მაღალი აკადემიური მოსწრების მქონე სტუდენტებისთვის.",
    url: "https://tsu.ge",
    eligibility: ["სტუდენტი", "GPA ≥ 3.7"],
  },
  {
    id: "g-freeuni-1plus",
    type: "uni",
    title: "Free Uni — 1+4 პროგრამა",
    org: "თავისუფალი უნივერსიტეტი",
    amount: "სრული დაფინანსება 1 წელი",
    deadline: "2026-07-20",
    description: "ერთწლიანი მოსამზადებელი პროგრამის ფარგლებში.",
    url: "https://freeuni.edu.ge",
    eligibility: ["აბიტურიენტი"],
  },
  {
    id: "g-erasmus",
    type: "intl",
    title: "Erasmus+ გაცვლითი პროგრამა",
    org: "ევროკომისია",
    amount: "თვიური სტიპენდია + ფრენა",
    deadline: "2026-03-01",
    description: "1-2 სემესტრიანი სწავლა ევროპის უნივერსიტეტში.",
    url: "https://erasmus-plus.ec.europa.eu",
    eligibility: ["სტუდენტი", "B2 ინგლისური"],
  },
  {
    id: "g-daad",
    type: "intl",
    title: "DAAD — გერმანული გაცვლა",
    org: "DAAD",
    amount: "თვიური სტიპენდია",
    deadline: "2026-04-15",
    description: "გერმანიის უნივერსიტეტებში სწავლა.",
    url: "https://www.daad.de",
    eligibility: ["სტუდენტი", "გერმანული ან ინგლისური"],
  },
  {
    id: "g-cartu",
    type: "private",
    title: "ქართუ ფონდის სტიპენდია",
    org: "ქართუ ფონდი",
    amount: "სრული / ნაწილობრივი",
    deadline: "2026-06-30",
    description: "სოციალურად დაუცველი, ნიჭიერი სტუდენტებისთვის.",
    url: "#",
    eligibility: ["სტუდენტი", "სოც. სტატუსი"],
  },
];

export const getGrant = (id) => grants.find(g => g.id === id);
